// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

declare const process: {
  env: Record<string, string | undefined>;
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Used by the CLI (migrate, db pull, studio) — needs prepared-statement
    // support, so this points at the non-pooled connection, not the pgbouncer one.
    url: process.env["DIRECT_URL"],
  },
});
