-- ============================================================================
-- 0800  Chat history and FAQ                         PORTABLE: Supabase + RDS
-- ============================================================================
-- Chat lives in the database, not the browser: the server saves every turn as
-- it happens and the page reloads the conversation from here.
--
-- When a technician marks an answer "resolved", its question is embedded and
-- kept in faq_entry. New questions are searched against it too (match_faq): a
-- similar resolved question brings back the passages that answered it and its
-- answer as a reference.
-- ============================================================================

create table if not exists chat_conversation (
  session_id  uuid primary key,                       -- the id in the browser's URL (/s/:sessionId)
  org_id      uuid not null references organization(org_id),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists chat_turn (
  turn_id      uuid primary key,                      -- generated by the client so a later "resolved" can name it
  session_id   uuid not null references chat_conversation(session_id) on delete cascade,
  seq          bigserial,                             -- order within the conversation
  role         text not null check (role in ('technician','agent')),
  text         text not null,
  gate_outcome text check (gate_outcome in ('answered','clarify','not_covered','conflict')),
  -- Everything else an agent turn needs to render again: sources, evidence image references,
  -- the clarification or not-covered card, verified, duration, plus what the FAQ needs:
  -- standalone_question and source_chunk_ids.
  turn_json    jsonb not null default '{}'::jsonb,
  resolution   text check (resolution in ('resolved','partly','not_resolved')),
  created_at   timestamptz not null default now()
);

create index if not exists chat_turn_session on chat_turn (session_id, seq);

create table if not exists faq_entry (
  faq_id           uuid primary key default gen_random_uuid(),
  org_id           uuid not null references organization(org_id),
  question         text not null,                     -- the standalone question (follow-ups already rewritten)
  answer           text not null,
  embedding        extensions.vector(1536) not null,  -- of `question`; same model as kb_chunk.embedding
  source_chunk_ids uuid[] not null default '{}',      -- the passages that grounded the answer
  citations        jsonb not null default '[]'::jsonb,
  source_turn_id   uuid,                              -- the agent turn that was marked resolved
  times_used       int not null default 0,
  last_used_at     timestamptz,
  active           boolean not null default true,
  created_at       timestamptz not null default now()
);

create index if not exists faq_entry_turn on faq_entry (source_turn_id) where source_turn_id is not null;

-- Nearest resolved questions by cosine similarity (0..1). Same shape as match_chunks:
-- the only place that uses the vector operator (rule P5).
create or replace function match_faq(
  p_org_id          uuid,
  p_query_embedding extensions.vector(1536),
  p_match_count     int              default 3,
  p_min_similarity  double precision default 0.0
)
returns table (
  faq_id           uuid,
  question         text,
  answer           text,
  source_chunk_ids uuid[],
  citations        jsonb,
  similarity       double precision
)
language sql
stable
set search_path = public, extensions
as $$
  select f.faq_id, f.question, f.answer, f.source_chunk_ids, f.citations,
         1 - (f.embedding <=> p_query_embedding) as similarity
    from faq_entry f
   where f.org_id = p_org_id
     and f.active
     and 1 - (f.embedding <=> p_query_embedding) >= p_min_similarity
   order by f.embedding <=> p_query_embedding
   limit p_match_count;
$$;
